stages:
    -docker-build

Build and push Docker image:
  stage: docker-build
  variables:
      GIT_STRATEGY: clone
      DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG}
  rules:
      - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
        variables:
            DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
      - when: always
  script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - chmod 777 .version.sh && . .version.sh
      - docker build -t "$DOCKER_IMAGE_NAME:$VERSION" .
      - docker push "$DOCKER_IMAGE_NAME:$VERSION"
      - docker image rm -f "$DOCKER_IMAGE_NAME:$VERSION"
  tags:
      - shell-linux-runner    
